version: '3.0'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - $FILE_PATH/$JOB_NAME/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    networks:
      - devops
  website:
    image: php-httpd:centos
    container_name: website
    ports:
      - $WEBSITE_PORT:80
    volumes:
      - $FILE_PATH/$JOB_NAME/website:/var/www/html
    networks:
      - devops
    depends_on:
      - mysql
  testing:
    image: node:latest
    container_name: node_test
    volumes:
      - $FILE_PATH/$JOB_NAME/test:/home/test
    networks:
      - devops
    depends_on:
      - website
networks:
  devops:
    driver: bridge
